Repository hassio-addons/addon-mqtt-io, pull requests merged in 2022-07, with the labels that each got.

#9 ⬆️ Upgrades add-on base image to 12.2.0
  mqtt-io/Dockerfile
  mqtt-io/build.yaml
Labels: dependencies

#10 Fix addon stop message
  mqtt-io/rootfs/etc/services.d/mqtt-io/finish
Labels: bugfix

#11 Fix gpio permission
  mqtt-io/config.yaml
Labels: bugfix

#12 Add link to HA discovery, update to latest release
  mqtt-io/DOCS.md
Labels: documentation

#13 ⬆️ Upgrades add-on base image to 12.2.1
  mqtt-io/Dockerfile
  mqtt-io/build.yaml
Labels: dependencies

#14 Some final documentation tweaks
  mqtt-io/.README.j2
  mqtt-io/DOCS.md
Labels: documentation

#16 Pre-install Adafruit DHT
  mqtt-io/Dockerfile
Labels: bugfix

#18 Force Adafruit_DHT to build for rpi2
  mqtt-io/Dockerfile
Labels: bugfix

#21 ⬆️ Upgrades python3 to 3.10.5-r0
  mqtt-io/Dockerfile
Labels: dependencies

#20 Set w1thermsensor requirement version to 2.0.0
  mqtt-io/requirements.txt
Labels: dependencies
